### ISSUE TITLE
Spigot update appears to have broken build

### ISSUE THREAD

**Issue by frizzbee30** [Multiverse/Multiverse-NetherPortals#103]
Hi, we have been using this plugin heavily for some time. However one of th elatest spigot commits appears to have broken it.Oddly it shows the target world as null, yet it is registerd in MV , accessible with MVTP and no errors are shown in the server load log for any of the associated plugins.

Spigot 1.8.6 (latest commit)

portals version build #685

error log, MV config and portals config in link
http://pastebin.com/qc7Yi2Uf

**Comment by TWSSYesterday** [comment]
"Caused by: java.lang.IllegalArgumentException: Cannot use location with null world!"

**Comment by frizzbee30** [comment]
hi, neither world is null though, both are valid, active worlds loaded into MV, both accessible via MVTP with no errors on loading. Setting up the nether portal link shows no error when the worlds are input, so why should one of them by null?

**Comment by TWSSYesterday** [comment]
Have you set the worlds up with MVNP?

**Comment by frizzbee30** [comment]
Hi, yes, if you see the config at the top of the pastebin you'll see the nether-portal config. It was working great, a perfect plugin for our setup and needs, but appears to have just 'stopped working'. We haven't had any player reports about it recently, so I am presuming it is with one of the latest spigot commits. However it was tested, working, and has been tested/used a few times since initial setup#

oddly, when I first checked the config it had reset for some reason to blank, but I quickly ran the config setup again to re link, but still didn't work

it does however give the 'portals are now linked' message even though it fails to work when stepping through

nether portals config
 
 
bounceback: true
worlds:
  vanilla:
    portalgoesto:
      NETHER: vanilla_nether


Thanks

**Comment by frizzbee30** [comment]
oddly this appears to be working again in test and live. I can't figure out why as no plugin or config changes have been made, and it failed on multiple reboots. It still generates a large amount of console spam as in the error log, but then after a second or two in the portal it transports through.
