### ISSUE TITLE
Non-player Entities Not Getting Transferred

### ISSUE THREAD

**Issue by SimonOrJ** [Multiverse/Multiverse-NetherPortals#111]
Players can go through the nether portal without any major problem.  They sometimes take half-a-heart of damage, but that isn't the biggest problem.  The huge problem I have on the latest Jenkins build is that entities are failing to go over from the second survival world's overworld portal to the second survival world's nether dimension.  I even tried manually linking the worlds with the "/mvnp link" command.  Am I configuring something wrong, or is it a bug?

**Comment by SimonOrJ** [comment]
Update: I realized that the things you throw into the second normal world's nether portal leads to the main world's nether portals.

**Comment by groovybluedog** [comment]
I'm finding nothing I throw in to the portal is getting to the other side even though the portal it was thrown through gobbles the items up.

**Comment by MrPistachios** [comment]
we have tried moving test llamas from world1 to world1_nether but they end up in world2 or world2_nether depending on which way you are going

**Comment by Jadiction** [comment]
Duplicate issue of https://github.com/Multiverse/Multiverse-NetherPortals/issues/72.
