### ISSUE TITLE
End and Nether Portals Spawn Players under the world or inside blocks

### ISSUE THREAD

**Issue by TheKekoslovakian** [Multiverse/Multiverse-NetherPortals#114]
My 1.10 Minecraft Server running Spigot 1.10 R0.1 (obviously) has been having problems with Nether Portals. I use Multiverse-NetherPortals and Multiverse-Portals with the regular Multiverse-Core. I have my Wild world linked with the Wild_nether world using MV-NetherPortals. Portals made near the Wild world spawnpoint work normally, almost, with the exception of often being put into blocks and suffocating and upon '/back' being put into a safe Nether environment. It's almost as if Multiverse's safe area detector broke and Essentials's works. But here's where the worse problems start. If a nether portal is built far away from the Wild world spawnpoint the nether portal brings people under the Nether, typically at the y value of around -11,000. I have no explanation for why this is. I really need help as this is server breaking and I have to have the server on maintenance. If anyone needs more specific info just reply to the thread and all help will be greatly appreciated! Also, no nether portals appear with the teleportation.

Plugin List: EssentialsX, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, ChestShop, PermissionsEx, WorldEdit, WorldGuard, PerWorldInventory, FUBS Random Teleport, Factions, MassiveCore, AutoSaveWorld, Vault

Result of /mv version -g:
[Link to Output](https://gist.github.com/anonymous/b27a90751fb3b683570a37360e51e5a7)

**Comment by afroman84** [comment]
STILL NOT SOLVED! SERVER-BREAKING issue, give this HIGH PRIORITY either we should remove MultiVerse-Core !

**Comment by Rayzr522** [comment]
I have the exact same problem, this is really killing my survival world on my server. Is MV even still being actively developed? Going into the nether from my survival world's spawn, my players are put 10 blocks under lava. It's actually almost right below where they're supposed to be put, but obviously they're not supposed to be stuck in blocks _below_ the lava.

Going out is a whole different story.... portals that are supposed to lead to bases now lead to a premature death from either falling 400 blocks down from the sky, or being spawned in the void at some ridiculous Y position like -3500.

I took a look at the good, and in theory it should be working 100% fine. Any ideas?

@FernFerret, @dumptruckman, anyone?

**Comment by afroman84** [comment]
Try to redo the world-nether link from scratch, remove the nether and link to the world in both ways.

**Comment by Rayzr522** [comment]
@afroman84 spawned in lava, died. Fun.

### Just some numbers for reference (X, Z)
Spawn Netherportal (Overworld): -231, 208
Spawn Netherportal (Nether): -34, -33
Spawn Netherportal (Nether expected): -33, 23
Spawn Netherportal (Overworld after exiting nether): -230, -232 (y: 210, should be 65)

Test Netherportal (Nether): -91, -181
Test Netherportal (Overworld): -756, -755 (y: -1450!?!?)

### Guesses
From what I can tell, the Z axis seems to be multiplied by -1 for the spawn netherportal when exiting, however with the test netherportal the Z should be -1,448. Just a note, that happens to be the... uh... wait.... Just realized that's what the Y value is when exiting, and I also just realized that the Y value when exiting the spawn netherportal is what the Z value is supposed to be... what the heck?!?

**Comment by Rayzr522** [comment]
### Updated numbers
    Overworld        : -232, 65,   210
    Overworld (exit) : -230, 210, -232
    Nether           : -34,  23,  -33
    Nether (expected): -34,  33,   23

**Comment by afroman84** [comment]
Try this, completely unlink and unload all worlds; backup your nether world; let the server generate a new nether folder; load worlds and link again them both ways; be sure you set the world type as nether for your nether world.

**Comment by Rayzr522** [comment]
I'm actually going to create a server completely from scratch with just Multiverse-Core and Multiverse-NetherPortals. Gonna rule that out first.

**Comment by afroman84** [comment]
I have occurred to your issue too, I solved rebuilding the nether again and
linked to world. It works, do not stop trying because of this issue

Il martedì 18 ottobre 2016, Rayzr522 <notifications@github.com> ha scritto:

**Comment by krustymk** [comment]
Ive re-created the nether and linked several times and still spawning inside blocks...

**Comment by Rayzr522** [comment]
@krustymk 
Hmmm, maybe try removing the nether world in MV, then re-importing it? Not actually deleting the files, just removing the record of it in Multiverse. [This command, right?](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#remove-command)

I never ended up trying to fix this, I just got too distracted with life, and other video games 😛 
I'd be glad to help you out though. This problem needs to be fixed.

**Comment by krustymk** [comment]
After the server restarted it all started working ok?.. Odd as i tried loads last night..

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
