### ISSUE TITLE
Portals Infnite Loop

### ISSUE THREAD

**Issue by Blackyvk** [Multiverse/Multiverse-NetherPortals#115]
When you link nether portals for example

world to nether
and
nether to world

You get stuck in a infinite loop

until you unlink 1 of the  worlds or someone force a /tphere

Spigot 1.9.4
Nether-Portals build 712
Core build 722

**Comment by tiploufdu76** [comment]
I have the same problem, just I don't link world with the command, I just rename them to world_nether but when anyone enter in a portal, the loading time inventory lets the player in the portal and when the inventory is loaded, the portal teleports the player again to the other dimension.

**Comment by SimonOrJ** [comment]
I think this craftbukkit commit can do something about it.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ae93d4fb492bc737466666087dcd49c9f775e40c

**Comment by Blackyvk** [comment]
Yes, That fixed it, i had already that commit but didnt notice until your comment... i'll close this now.

Thanks!
