### ISSUE TITLE
Strange issue with end portal

### ISSUE THREAD

**Issue by CoolLord22** [Multiverse/Multiverse-NetherPortals#123]
If you use end portals for a world that doesn't have an end setup, this message gets spammed like crazy in console and the player just glitches on the dirt screen (like the empty background)

http://pastebin.com/UFJ291Mi

**Comment by CoolLord22** [comment]
This was fixed by https://github.com/Multiverse/Multiverse-NetherPortals/pull/117 but in the latest dev build the issue returned (https://ci.onarandombox.com/job/Multiverse-NetherPortals/) any word on if this will be fixed? @FernFerret / @dumptruckman

**Comment by Jadiction** [comment]
Duplicate of https://github.com/Multiverse/Multiverse-NetherPortals/issues/104
