### ISSUE TITLE
Wrong yaw in portals

### ISSUE THREAD

**Issue by WyRe** [Multiverse/Multiverse-NetherPortals#124]
After create a portal and ignite it with lighter, I get nether portal blocks with wrong yaw as you can see in the picture:

![2017-04-21_23 00 20](https://cloud.githubusercontent.com/assets/4059108/25296077/c6de0df2-26e6-11e7-8096-d2d75ef59bbb.png)

Also the people teleport through the portal with the same yaw.

Thank you.

**Comment by FernFerret** [comment]
I though (unless something has changed) those tiles were client side? I do know that the player's yaw is controllable based on the portal exit. If you require more control over pitch yaw and roll, check out [Exact Destinations](https://github.com/Multiverse/Multiverse-Core/wiki/Destinations#exact-destinations).

At a minimum, this issue doesn't really belong here (as I started with, I'm pretty sure it's not really a MV thing at all but probably another mod/server incompatibility or something) but probably belongs in MV-Portals. MV-NetherPortals simply allows linking/scaling of worlds.
