### ISSUE TITLE
world without nether

### ISSUE THREAD

**Issue by im4g1n4t1onsX** [Multiverse/Multiverse-NetherPortals#126]
so i made a factions world with spawn and everything. When i imported it into my server it had no nether or end. how do i create one that links to my faction world. because when i create a nether portal i cant go in it.
Please help

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
