### ISSUE TITLE
No portal autocreation

### ISSUE THREAD

**Issue by mcbloch** [Multiverse/Multiverse-NetherPortals#127]
If you walk through a nether portal you spawn at the correct location in the nether but no portal is generated or if there is already a portal in range it is not linked. Same bug appear in opposite direction Nether => normal world.

Everything works fine on the default map with the default nether.

I tried different setups, making the worlds in multiverse, importing a complete working set. Linking them via 'mvnp link', no linking, ...
Nothing seems to work.

**Comment by Rikaelus** [comment]
Having this issue as well.
I created a _nether world and a gateway in the normal world only to end up inside the ground. The spawn location was consistent so I set up a gate in the Nether at the approximate location for 2-way travel. It works, though returning to the normal world doesn't spawn me quite in the right place. Good enough to work with but clearly the mechanics are broken.

**Comment by fnc12** [comment]
Me too. How to fix it?

**Comment by seansbar** [comment]
I also have this issue, It will also let you swan into lava lakes too!
Paper spigot 1.12.2
MV-core 2.5.0-snapshot-b725
MV-NetherPortals 2.5.0-snapshot-b714

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
