### ISSUE TITLE
Entities not syncing between nethers.

### ISSUE THREAD

**Issue by jjhhgg100123** [Multiverse/Multiverse-NetherPortals#128]
This is a bit detailed, so I'll give names to the worlds.

World = W1
World_nether = WN1

World2 = W2
World2_nether = WN2

I have synced the W2 and WN2 together, but when mobs/items are thrown through the portal in W2, they go to WN1. When things go through in WN2, they go to W1. Players are fine however.

Edit:
It seems there is another bug report that is a bit older still open. I'll leave this up to confirm that this bug still exists.

**Comment by MrPistachios** [comment]
We have been having this same issue for a while now, do you have a link to the original post?

**Comment by ArchGoddess** [comment]
I've also had this issue but not just with the nether but also the end portal as well. Tested all through out 2018... poor test llamas didn't have a chance...
Confirmed that it still happens in 1.13.2 as well.

**Comment by jjhhgg100123** [comment]
@ArchGoddess and @MrPistachios 

It's #72 from 2013. To be completely honest, I doubt this will get fixed.

**Comment by Jadiction** [comment]
Duplicate issue of https://github.com/Multiverse/Multiverse-NetherPortals/issues/72.
