### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by BrettplayMC** [Multiverse/Multiverse-NetherPortals#129]
When using the latest AB on the bukkit page, I don't get tped to the world.  Spigot 1.8.8.

**Comment by BrettplayMC** [comment]
Wait does allow-nether need to be enabled in the server.properties for this to work?

**Comment by BrettplayMC** [comment]
.

**Comment by BrettplayMC** [comment]
.

**Comment by BrettplayMC** [comment]
.

**Comment by dumptruckman** [comment]
yes.

**Comment by BrettplayMC** [comment]
Well the problem is, my default world is set to "Lobby" and if I enable that, a nether world will be created for "Lobby" and I only want one for another world.  Is there any way to fix that?

**Comment by dumptruckman** [comment]
If you don't wish to use the Lobby_nether, you can always set `keepspawninmemory` to false and remove access permissions for it.

**Comment by BrettplayMC** [comment]
But is there any way to keep the world from generating?  Could it be changed by having my Spigot jar edited?  btw thanks so much for helping.

**Comment by dumptruckman** [comment]
A custom Spigot jar could do it sure. Another option would be to change your default world but you have to be very careful doing it that way.

**Comment by BrettplayMC** [comment]
Do you know anyone who could make a special Spigot jar for me?
