### ISSUE TITLE
A couple bugs I discovered

### ISSUE THREAD

**Issue by Peridot03** [Multiverse/Multiverse-NetherPortals#130]
A couple bugs I discovered is that when you link a world to a foreign nether, and use a portal to go there, it doesn't create a nether portal in the nether, however, when i made a link to go from the nether back to that world, it created a portal randomly in the world
A second one, is that the portals dont always teleport you in a safe spot (I had players being warped into walls and not being able to do anything)

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
