### ISSUE TITLE
Destination Nether/End Portal Not Generating

### ISSUE THREAD

**Issue by WesleyRTech** [Multiverse/Multiverse-NetherPortals#133]
Hi. I have created two worlds: survival0 and survival0_nether. I have linked them with Multiverse Nether Portals.

When I go through a portal in Survival0, I can spawn in invalid (deadly) locations in the nether. Not only that, but a "destination" portal does not generate in Survival0_nether. So, my problem is that a portal does not spawn in the nether when I go through one in the overworld.

The same is true in the reverse direction - a portal made in the nether does not spawn in the overworld when I go through it.

I have tried reinstalling both Multiverse Core and Nether Portals, linking and unlinking the nether, deleting the nether world and making a new one, and restarting the server multiple times.

I was using this system without issue until it just decided to bug out for no apparent reason.

Any help would be greatly appreciated!

**Comment by GodGMN** [comment]
I don't know how does github work at all lol, sorry if I'm not supposed to answer there but same for me.

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
