### ISSUE TITLE
Bounceback

### ISSUE THREAD

**Issue by Raphy123** [Multiverse/Multiverse-NetherPortals#135]
Hi 

If bounceback is false, message display always when I go on a portal who works
I use an other plugin for my other portal

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
