### ISSUE TITLE
Please make compatible with AdvancedPortals plugin

### ISSUE THREAD

**Issue by axemwa** [Multiverse/Multiverse-NetherPortals#138]
Can you please make compatible/add support with/for AdvancedPortals plugin?
https://www.spigotmc.org/resources/advanced-portals.14356/

Atm when custom portals are made using AdvancedPortals, Multiverse-Netherportals prevents the player from entering the portal because it exspects the portal to be linked to a nether world even though in this case one doesn't need to be made :)

**Comment by Jadiction** [comment]
This is unlikely to happen, but if you'd like more information, you may ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support).

**Comment by axemwa** [comment]
Thanks for replying, that's ok I might just use this plugin on a separate server to my main one then it will still work that way ;)
