### ISSUE TITLE
End Portal Not Teleporting to THE END spawn

### ISSUE THREAD

**Issue by jordanwilliams1** [Multiverse/Multiverse-NetherPortals#139]
End portal will spawn you randomly (Most likely in the void.)

**Comment by oranges13** [comment]
We have this issue too and it's killing players.

**Comment by jordanwilliams1** [comment]
@oranges13 ik :(

**Comment by Narimm** [comment]
Its due to the loss of the TravelAgent ...

**Comment by oranges13** [comment]
So, upgrading to the latest version seems to have solved this issue.
