### ISSUE TITLE
Spigot 1.14.1-R0.1-SNAPSHOT breaks the plugin? 

### ISSUE THREAD

**Issue by graysonlee123** [Multiverse/Multiverse-NetherPortals#141]
It seems that no matter what builds I try, I get "Could not pass event PlayerPortalEvent to Multiverse-Core" errors. The plugin's commands work, and I don't have any issue running the commands or linking the worlds. However, the portals A) don't go to the correct worlds (they just link back to the regular world_nether), and B) don't spawn you in a safe area as well as do not generate a portal on the other side. I try using dev builds of MVCore and MVNP.

Any pointers?

**Comment by MrPistachios** [comment]
Im having the same issue on the latest dev build and latest paper version of 1.14.2
ERROR Could not pass event PlayerPortalEvent to Multiverse-NetherPortals v3.0.0-SNAPSHOT-b749

**Comment by Narimm** [comment]
Fixed in Pull #143 
Download a working version on 
https://jenkins.addstar.com.au/job/MultiVerse-NetherPortals/

**Comment by MrPistachios** [comment]
> 
> 
> Fixed in Pull #143
> Download a working version on
> https://jenkins.addstar.com.au/job/MultiVerse-NetherPortals/

Thank you! I loaded it in and will give it a try

**Comment by Narimm** [comment]
@MrPistachios this is now fixed in mainstream and I have removed that build
