### ISSUE TITLE
Could not pass event PlayerPortalEvent to Multiverse-NetherPortals v3.0.0-SNAPSHOT-b749

### ISSUE THREAD

**Issue by kaniesha** [Multiverse/Multiverse-NetherPortals#142]
Spigot: git-Spigot-093165d-ba575a5 ver 1.14.2-R0.1-SNAPSHOT
Multiverse-NetherPortals v3.0.0-SNAPSHOT-b749

Reposting here because I posted in Multiverse-Core by mistake.

Error:
https://gist.github.com/kaniesha/bfa5a9ca890131cb7978e81e21c13938

**Comment by MrPistachios** [comment]
same issue using 1.14.2 paper and latest multiverse nether portals

**Comment by Narimm** [comment]
Would be resolved by Pull Request #143 

You can download a build with this PR on https://jenkins.addstar.com.au

**Comment by Jadiction** [comment]
This has been fixed in 4.0.0, please update to the latest dev build.
