### ISSUE TITLE
Possibility to disable the 'no linked world' message

### ISSUE THREAD

**Issue by Waterman1001** [Multiverse/Multiverse-NetherPortals#145]
Hey,

Could you please add the option to disable the message:
"No specific end world has been linked to this world and '<WorldName>_the_end' is not a world".

to the config.yml file?

It would help me a lot, since it saves spam in chat.
Thank you so much in advance!
Kind regards,
Waterman1001

**Comment by Jadiction** [comment]
I agree this should be a configuration.

**Comment by axemwa** [comment]
Totally agree, as well as making the "this portal goes nowhere" message optional, it keeps spamming when I attempt to use the portal blocks for other destinations and/or worlds using another plugin (AdvancedPortals). Maybe instead could even add a `blacklisted-worlds:` section in config for portals in worlds that you don't want MVNP affecting which not only prevent unnecessary messages but any unnecessary checks that the plugin does as well

**Comment by SemicolonStruggles** [comment]
Would also very much like to see this. 

I found the code causing the message, seems like it should be an easy fix. I might give it a shot soon, have never done any plugin writing/modification so don't get your hopes up :)

https://github.com/Multiverse/Multiverse-NetherPortals/blob/465f60763b88820bdd45c385e9e854ac6676702d/src/main/java/com/onarandombox/MultiverseNetherPortals/listeners/MVNPEntityListener.java#L172

**Comment by Jadiction** [comment]
@SemicolonStruggles Feel free to submit a PR and I'll ask Dumptruckman to review it & merge it if it met his standards.
