### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by SilverKat** [Multiverse/Multiverse-NetherPortals#148]
When I start my server it says Multiverse-NetherPortals could not be loaded. Please get back to me if this can be fixed I need this for my server. I have tried the most recent version (4.1.0) and the one before that (4.0.0). Thanks.

**Comment by Konata400** [comment]
What version is your minecraft server?

**Comment by SilverKat** [comment]
1.15

**Comment by BigLife5** [comment]
Hey, 

i got a similar problem..
I uploadet the server log on Pastebin
https://pastebin.com/KLJnjUXm

**Comment by Konata400** [comment]
> Hey,
> 
> i got a similar problem..
> I uploadet the server log on Pastebin
> https://pastebin.com/KLJnjUXm

Wrong your are using snapshot-javadoc.jar is not the plugin.

Please use this https://ci.onarandombox.com/job/Multiverse-NetherPortals/764/artifact/target/Multiverse-NetherPortals-4.1.1-SNAPSHOT.jar
