### ISSUE TITLE
End portals not working

### ISSUE THREAD

**Issue by Elitekrieger** [Multiverse/Multiverse-NetherPortals#149]
I have a world which is linked correctly with a nether and end, but the end portal in the end doesnt teleport me back.

My worlds:
1SW
1SW_nether
1SW_the_end
Links:
Nether: 1SW->1SW_nether; 1SW_nether->1SW
End: 1SW->1SW_the_end; 1SW_the_end->1SW

Spigot: 1.15 newest build

**Comment by nicegamer7** [comment]
This is a known issue, please see the issue mentioned above for a fix.
