### ISSUE TITLE
problem with creating netherportal/end spawn

### ISSUE THREAD

**Issue by sujeeban** [Multiverse/Multiverse-NetherPortals#150]
I'm having a problem with multiverse nether portals.. when a player goes through the nether portal, they just fall down and kills themselves. no portal is being created on nether.. same problem with the end.

**Comment by sujeeban** [comment]
i have 1.8.8 - 1.15.2 server with multiverse core and nether portal 2.4 version.

**Comment by benwoo1110** [comment]
Which exact Minecraft version is your server running on?

Go to the die load page and look for a version compatible with it.

**Comment by benwoo1110** [comment]
Closing this due to lack of information.
