### ISSUE TITLE
Nether portal teleporting to the wrong world

### ISSUE THREAD

**Issue by swat077** [Multiverse/Multiverse-NetherPortals#151]
Hey, 
So i'm running spigot 1.15.2 and the latest version of multiverse.
I have two worlds and we're mainly playing on the second world.
When someone goes to the nether and they want to return they get teleported to the first world.
I found here that the nether portals are intended to teleport from the nether to the primary world and not to secondary worlds. Is there anything I could do to change it ? 
Much thanks

**Comment by benwoo1110** [comment]
have you create a nether world named <secondworldname>_nether? And have you tried linking the nether portals using mv-netherportals?

**Comment by AgentShield233** [comment]
I'm having this problem also, but I do have mv-netherportals. It's still not working (The whole plugin isn't working)

**Comment by benwoo1110** [comment]
can you check that use are using the latest version of mv-core 4.1.0 (same for the rest of the mv plugins)
https://dev.bukkit.org/projects/multiverse-core

**Comment by AgentShield233** [comment]
Yes, I am. I found the problem is No new plugins are working. It installs the .jar file, but not the plugin folder. any ideas?

**Comment by benwoo1110** [comment]
Most likely issue is with your server host, or if you are hosting on your own pc, try delete, redownload and reinstall the jars.

**Comment by AgentShield233** [comment]
I'm using server.pro (paid for) and yes I've tried that

**Comment by benwoo1110** [comment]
you will have to check with your server host why plugin is not installing correctly then, since its all new plugins not working and not only mv plugins. (as you stated previously)

**Comment by AgentShield233** [comment]
yes, ok. I will contact them.
