### ISSUE TITLE
request

### ISSUE THREAD

**Issue by DarkLord3001** [Multiverse/Multiverse-NetherPortals#152]
Hello, 
I want to ask if it possible to make a system which allows an user to enter a seperate world for only a few hours. Exsampel: User buys a ticket for a farmworld which allows them to enter this world for a limited time
sincerely
Niclas (DarkLord3001)

**Comment by MrPistachios** [comment]
Maybe with permissions that expire from like luckperms?

**Comment by DarkLord3001** [comment]
thx i will try this
