### ISSUE TITLE
Plugin not enabled on startup.

### ISSUE THREAD

**Issue by DoggoTaco** [Multiverse/Multiverse-NetherPortals#153]
Hello! My server is using Paper 1.15.2 and we have the latest version of multiverse core, portals, and nether portals. But the plugin is disabled and we cannot go to the nether through a different world(survival1), it leads us to our default world(spawn). Is there a solution to this, or is the plugin broke? Thanks! (i uploaded the log, if that helps)
[latest.log](https://github.com/Multiverse/Multiverse-NetherPortals/files/4478404/latest.log)

**Comment by dcoshea** [comment]
> we have the latest version of multiverse core

That's not what your log says:

    [20:15:40] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v3.0.0-SNAPSHOT-b760
    ....
    [20:15:58] [Server thread/ERROR]: [Multiverse-Portals] Your Multiverse-Core is OUT OF DATE
    ...
    [20:15:59] [Server thread/ERROR]: [Multiverse-NetherPortals] Your Multiverse-Core is OUT OF DATE

It looks like your Multiverse-Inventories plugin is old too.  I don't know if that matters, but the outdated Multiverse-Core definitely does.

**Comment by benwoo1110** [comment]
you can download the latest version of all mv plugin here: (supports 1.15.2)

Multiverse-Core (Required for the sub-module plugins below)
https://dev.bukkit.org/projects/multiverse-core
Multiverse-Portals
https://dev.bukkit.org/projects/multiverse-portals
Multiverse-NetherPortals
https://dev.bukkit.org/projects/multiverse-netherportals
Multiverse-SignPortals
https://dev.bukkit.org/projects/multiverse-signportals
Multiverse-Inventories
https://dev.bukkit.org/projects/multiverse-inventories

**Comment by DoggoTaco** [comment]
Ah, well now their enabled. Co must of got it from the wrong source. Thanks!
