### ISSUE TITLE
Entities not being teleported to Nether/End

### ISSUE THREAD

**Issue by Scindix** [Multiverse/Multiverse-NetherPortals#160]
Hi,
I'm using SpigotMC 1.15.2 (i.e. based on Bukkit 1.15.2) with Multiverse NetherPortals v4.1.0 and it works fine for teleporting players between overworld, the Nether and the End.

However if entities touch a portal block they just stay there as if there was no portal. They are not teleported to another dimension, not even to the wrong one. Tested with items and mobs. This is contrary to how it works in vanilla (also tested in comparison).

The console doesn't spit out any errors.

I'm not sure if I'm using the wrong configuration, if this is a bug or if this is even supposed to work. Some insight on this would be nice. I'm even willing to help on a fix if there is something to fix. But right now I'm just wondering what origin my issue has.

**Comment by benwoo1110** [comment]
see #72 its a known issue we are working on

**Comment by Scindix** [comment]
I've seen issue #72 and thought mine was different as entities aren't teleported at all. Whereas in #72 people report entities to be teleported to the wrong dimension.

However after a lot of testing I found the cause for the different behaviours: I've installed Multiverse-Inventories so that Inventories will be shared between overworld, Nether and the End, but not between different overworlds. Disabling Multiverse-Inventories gives the same behaviour as in the mentioned issue. Probably the plugin tries to teleport the entity outside of the defined group and Multiverse-Inventories tries to prevent that.

So it's really just #72, but in disguise. Just wanted to clarify that in case anyone else comes across this. Thanks for your efforts btw.

Anyway I found a workaround in my case. Renaming the worlds in the most important group to "world", "world_nether" and "world_the_end" makes it work at least for these specific worlds.

**Comment by nicegamer7** [comment]
Something I've realized while trying to fix #72 is that entities are only TP'd via nether portals if `allow-nether` in `server.properties` is on, and via end portals if `allow-end` in `bukkit.yml` is on.

**Comment by SoRadGaming** [comment]
This issue still persists with Paper 110 for 1.16.1, Using the Latest Discord Devbuild (22 of July 2020 - 8:06AM)

**Comment by benwoo1110** [comment]
did you try this exact build: https://github.com/Multiverse/Multiverse-NetherPortals/pull/156#issuecomment-641366973

**Comment by SoRadGaming** [comment]
Tried that build, now they go through, yet can't be found on the other side. I have no idea where they go.

**Comment by nicegamer7** [comment]
This is fixed in the latest release.
