### ISSUE TITLE
Linking a world to itself sometimes doesn't work

### ISSUE THREAD

**Issue by j-tai** [Multiverse/Multiverse-NetherPortals#165]
If you link a world to itself, for example with the following command:

```
/mvnp link nether myworld myworld
```

The nether portals in the `myworld` world sometimes do not get disabled; they instead go to Bukkit's default nether world, such as `world_nether` (even if `myworld_nether` exists!).

Steps to reproduce (try on a test server with no other worlds or links):

1. Create a new world which is not the default world:

        /mvcreate myworld normal -t flat

2. Link that world to itself:

        /mvnp link nether myworld myworld

3. Explicitly link the default world, nether, and end to each other:

        /mvnp link nether world world_nether
        /mvnp link nether world_nether world
        /mvnp link end world world_the_end
        /mvnp link end world_the_end world

4. Go to the `myworld` world and build a nether portal.
5. Go through the nether portal.
    → You will be teleported to `world_nether`, instead of being denied use of the portal.

Multiverse-Core version 4.1.1-SNAPSHOT-b777  
Multiverse-NetherPortals version 4.1.1-SNAPSHOT-b764
Spigot version git-Spigot-a99063f-fad2494 (MC: 1.15.2)

**Comment by nicegamer7** [comment]
Can you try the test build available [here](https://github.com/Multiverse/Multiverse-NetherPortals/pull/163#issuecomment-640883945) and let me know if this still happens?

**Comment by j-tai** [comment]
It still sort of happens. It allows me through the portal (it doesn't kick you back and display a message as expected), but the portal links to itself. So rather than disabling the portals, the world is literally linked to itself. This is a problem for end portals, since it will generate the 5x5 obsidian platform when you go through it, deleting part of the end portal.

**Comment by nicegamer7** [comment]
Sorry I don't really understand. What difference did the build I linked make?

**Comment by j-tai** [comment]
The build you linked causes the portal in `myworld` to link to itself instead of linking to `world_nether`. Both behaviours are problematic.

**Comment by nicegamer7** [comment]
Alright, thanks for clarifying. Just so we're on the same page, what do you think is the expected behaviour?

I would think it should not allow you to link to the same world.

**Comment by j-tai** [comment]
I expected it to physically throw me back and display a message that reads,

> No specific nether world has been linked to this world and 'myworld_nether' is not a world.

When I run the command `/mvnp link nether creative creative` (linking the world to itself), it displays

> NOTE: You have successfully disabled NETHER Portals in myworld

So I expect the nether portals in `myworld` to be disabled.

**Comment by nicegamer7** [comment]
Oh nice catch! I'm new here so I didn't realize that it's supposed to disable portals (I'm new here).

This should be an easy fix. I'll upload a test build for you in about five minutes.

**Comment by j-tai** [comment]
It's alright! I think that feature is undocumented. In fact, I had to read the code in order to find it.

**Comment by nicegamer7** [comment]
I just uploaded a new test build in the PR linked above, give it a try and let me know!

Thanks for reporting this issue. I'll make sure to document this feature :)

**Comment by j-tai** [comment]
Yup, that build fixes it. Thanks!

**Comment by nicegamer7** [comment]
Awesome! Thanks for reporting!

I'll keep this issue open until that PR gets merged.
