### ISSUE TITLE
MV nether portal doesn't seem to be working on spigot 1.16.1 and paper 1.16.1

### ISSUE THREAD

**Issue by samuelvitry** [Multiverse/Multiverse-NetherPortals#166]
I got the latest version of paper and mv nether portal, I got many world but most importantly :
- world  (default)
- world_nether   (default)
- fac1
- fac1_nether.
Ive linked nether portal fac1 -> fac1_nether and fac1_nether -> fac1 but when I take a nether portal in fac1 I get tp to world_nether, so when I take the portal back I get tp to world which is a problem cause this is a void world so my player get tp in the middle of the void. Also I'v tried to relight the portal and to go far away to get out of the nether portal cache of minecraft and I've tried to link world_nether to fac1 and that still doesn't fix the issue.
Thank you for reading me and sorry for bad english.

**Comment by samuelvitry** [comment]
Ok the problem is fix because now the player can only fix access nether and end on the default world.

**Comment by benwoo1110** [comment]
So I assume its fixed?

**Comment by samuelvitry** [comment]
I think...
