### ISSUE TITLE
Portals don’t link up properly 1.16.1

### ISSUE THREAD

**Issue by DeDiamondPro** [Multiverse/Multiverse-NetherPortals#167]
Hello,

My portals do not link up properly and this is what it says when I got thru a portal in the command prompt.

[Mon, 29. Jun 2020 13:34:32 GMT WARN] [Multiverse-NetherPortals] TravelAgent not available for PlayerPortalEvent for DeDiamondPro
[Mon, 29. Jun 2020 13:34:32 GMT WARN] [Multiverse-NetherPortals] TravelAgent not available for PlayerPortalEvent for DeDiamondPro. Their destination may not be correct

**Comment by nicegamer7** [comment]
What do you mean they do link up properly?

**Comment by DeDiamondPro** [comment]
> What do you mean they do link up properly?

All portals link up to the portal within the search distance of spawn

**Comment by DeDiamondPro** [comment]
Made my portal at the wrong location
