### ISSUE TITLE
Getting respawned at nether portal after dying in Nether (1.16)

### ISSUE THREAD

**Issue by jeslinmx** [Multiverse/Multiverse-NetherPortals#168]
I'm trying to set up a private world (overworld+nether+end) but have been experiencing some weird behaviour around respawning mechanisms. Here's what I've found so far:

- In this new world (let's call it testworld), if I die in the overworld, I respawn at my bed or at world spawn (expected)
- If I enter testworld_nether and perish there, I respawn in testworld (expected), at the nether portal entrance, instead of my bed (unexpected)
- If I try this in the default worlds (world, world_nether) generated by Paper, it works as expected (dying in either world or world_nether brings me back to my bed in world).
- worlds.yml config is identical between world and testworld, and between world_nether and testworld_nether, except for the seed.

To further muddy the water, I was also playing around with keepInventory true at the same time (although the above problems occur even without keepInventory), and found these:

- In world and world_nether, setting keepInventory true in world is sufficient (dying in either world or world_nether lets me keep my items).
- In testworld, setting keepInventory true and dying in testworld (overworld), I keep my items.
- If I set keepInventory true in both testworld and testworld_nether, and die in testworld_nether, I lose my items.

I tried to replicate this in my 1.15 backup, since I recognize there may yet be some bugs from the brand new release and incompatibilities with MV4.1, but I had other troubles altogether (my inventory wasn't transferring between nether and overworld), so I suspect lack of sleep might be playing a factor and I'm missing something stupid. Could anyone lend a hand?

Server setup:

- Paper 1.16 build 24
- MV-Core, NP, Portals 4.1.0
- MV-Inventories 3.0.0
- LuckPerms 5.1.26
- WorldEdit 7.1.0
- EssentialsX 2.17.2.77

**Comment by jeslinmx** [comment]
Aaaaand it turns out I forgot to set up world groups in MV-Inventories. Although that doesn't really explain how come it works in the default worlds. Closing this issue!

**Comment by nicegamer7** [comment]
We're glad you figured it out (and that there's no bug lol). As for why it works with the default worlds, it's most likely because MV Inventories automatically groups them.
