### ISSUE TITLE
Only one portal works

### ISSUE THREAD

**Issue by RMalfroid** [Multiverse/Multiverse-NetherPortals#170]
Don't know how to title this correctly, but I've successfully set up portal in the overworld and in the nether. Any portal can be used to get to the nether, and any portal can be used to get back to the overworld, but when coming back to the overworld, you'll only come out of one single portal everytime no matter where the portal is in the nether. How do I set this up so any player can build a portal in the overworld and come back out of that same portal they built when coming back from the nether?

**Comment by nguyenab** [comment]
I have this issue too on PaperMC 1.16.1

**Comment by SoRadGaming** [comment]
I have the same issue, even on my no Plugins Server, I don't think this is a Multiverse Issue but a Paper/Bukkit one.

**Comment by nicegamer7** [comment]
Please try the MV Core and NetherPortals builds pinned in the MV Discord server.

**Comment by benwoo1110** [comment]
It doesnt look like an MV issue, so I will be closing it. If you still face issues, you can open a new issue or join our discord at https://discord.gg/NZtfKky
