### ISSUE TITLE
Plugin is not loading

### ISSUE THREAD

**Issue by eliyash31** [Multiverse/Multiverse-NetherPortals#178]
Minecraft Version : 1.16.1
plugin version: 4.1.0

19.09 11:39:01 [Server] ERROR Could not load 'plugins/Multiverse-NetherPortals-4.1.0 .jar' in folder 'plugins'
19.09 11:39:01 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
19.09 11:39:01 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
19.09 11:39:01 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
19.09 11:39:01 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211]
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO ... 7 more
19.09 11:39:01 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.onarandombox.commandhandler.Command
19.09 11:39:01 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_211]
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
19.09 11:39:01 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
19.09 11:39:01 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
19.09 11:39:01 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_211]
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.1.jar:git-Paper-138]
19.09 11:39:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.1.jar:git-Paper-138]

**Comment by benwoo1110** [comment]
You probably have wrong/missing install of multiverse-core. Get latest build from http://ci.onarandombox.com/view/Multiverse/
