### ISSUE TITLE
Build/test errors

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-NetherPortals#189]
Last successful build (#773), 11 hr ago
Last failed build (#774), 9 hr 26 min ago

**Comment by benwoo1110** [comment]
Yes we know, we were planning a 4.2.0 release very soon... but it was past 2am so hopefully tonight it will be done!

**Comment by benwoo1110** [comment]
Also, dont always have to open issue on dev build errors, bcu its experimental and so fail at times.

**Comment by SlimeDog** [comment]
OK, thanks.
