### ISSUE TITLE
Advancement warning when traversing to worlds even when advancements are disabled.

### ISSUE THREAD

**Issue by mibby** [Multiverse/Multiverse-NetherPortals#219]
### Information

* **Server version:** Yatopia dev 1381 (Paper 1.16.5)

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/30e37e74a476416ca665c025a04e1990

Multiverse-NetherPortals dev 799.

### Details
I was **`<able>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Multiverse-NetherPortals tries to reward advancements even when advancements are disabled, causing a warning message. This seems to be caused by https://github.com/Multiverse/Multiverse-NetherPortals/commit/431077fb0e36e6580198b9f30271a1f5246337dc.

```
[07:15:54] [Server thread/WARN]: [Multiverse-NetherPortals] No advancement found for target criteria: entered_nether
[07:16:54] [Server thread/WARN]: [Multiverse-NetherPortals] No advancement found for target criteria: entered_nether
[07:23:04] [Server thread/WARN]: [Multiverse-NetherPortals] No advancement found for target criteria: entered_nether
[07:26:06] [Server thread/WARN]: [Multiverse-NetherPortals] No advancement found for target criteria: entered_nether
```

In Spigot.yml, I have advancements disabled.
```
advancements:
  disable-saving: true
  disabled:
  - '*'
```

I have also ran ``/gamerule announceAdvancements false`` in all worlds.

**Steps to reproduce**  
Enter nether or end.

**Expected behavior**  
No warning when traversing worlds.

**Comment by nicegamer7** [comment]
I think we're going to be reverting that change, so I'll keep this open either till that happens or till we put in some way of checking that advancements are enabled.

**Comment by benwoo1110** [comment]
Actually, there isn’t a need to revert, can just simply set the logging message to debug.

**Comment by benwoo1110** [comment]
advancement disabled just means well it’s not found so I don’t see an issue with the message logged, just warning level probably put off some ppl.

**Comment by nicegamer7** [comment]
Ah, I didn't notice we were the ones printing the error 😝. I thought it was the server.
