### ISSUE TITLE
Nether Portals doesn't work

### ISSUE THREAD

**Issue by NoboKik** [Multiverse/Multiverse-NetherPortals#221]
### Information

* **Server version: 1.16.4**

### Help request

**Problem**
Can't get NetherPortals to work.

**What I have tried**
Tried to use nether portal with OP,
Tried to change config in server.properties - allow-nether=true (set to false then back to true)
Tried to use main world (that one in server.properties - level-name=world)

**Comment by nicegamer7** [comment]
Please provide the link given by `/mvv -p`.

**Comment by NoboKik** [comment]
Fixed this!
