### ISSUE TITLE
Multiverse Nether portals End Unlinks after restart

### ISSUE THREAD

**Issue by Manfruity** [Multiverse/Multiverse-NetherPortals#226]
### Information

* **1.16.4:** 

* **version 2.9:** 

* **Server log:** 

### Help request

**Problem**

Whenever i restart my server it unlinks the end portals
So after restart when u try go into a portal it would just say Cant enter since its not linked

**What I have tried**

Nothing since idk what i can do
**Screenshots**

**Comment by benwoo1110** [comment]
Update to latest dev builds it was fixed. http://ci.onarandombox.com/view/Multiverse/job/Multiverse-NetherPortals/

NOTE: Next time please follow the issue template, it's not for you to ignore.
