### ISSUE TITLE
Portals only work from Nether/End not from Overworld

### ISSUE THREAD

**Issue by LordGrafnus** [Multiverse/Multiverse-NetherPortals#227]
### Information

* **Server Version:** Paper 1.16.5

* **Full output of `/mv version -p`:** Lastest Dev build

* **Server log:** [https://gist.github.com/LordGrafnus/8d7a44591a146c49c570e131fd56f76a](https://gist.github.com/LordGrafnus/8d7a44591a146c49c570e131fd56f76a)

### Help request

**Problem**
I can use a Netherportal in the Nether to get back to the overworld. But I cannot use a Netherportal in the overworld to get into the Nether. The End portals do not work as well.

**What I have tried**
Linking the world with one another.
Only linking in one direction.

**Comment by benwoo1110** [comment]
Please follow the issue template. Server logs, and output of `/mv version-p` is missing.

**Comment by LordGrafnus** [comment]
There you go updated the request

**Comment by benwoo1110** [comment]
You need to link the portals both ways, so `Utopia -> Destopia` in your case. As for end portals, I don't see any linking done so link them if you want them to work. You may need to set respawn world if you don't respawn  at overworld from end/nether, see https://github.com/Multiverse/Multiverse-Core/issues/2160

**Comment by LordGrafnus** [comment]
Yeah I know. I removed the link for test purpose. It still does not work if they are linked. As I already stated above

**Comment by LordGrafnus** [comment]
I linked the world again, tried it, still not working. I edited the request again. New Startup log now with the try to use a portal.

**Comment by benwoo1110** [comment]
Tested it on latest version of papermc and MV installed, cannot reproduce, netherportals worlds just fine with linked both way. So I can only see an issue with your setup.

1. Ensure that `allow-nether` is true is server.properties
2. The default nether is loaded.
3. Link them correctly (2 ways not just one) as I said.
4. Test with only mv installed, plugin conflict could have cause it.
5. You are using some 5.0.0 UNKNOWN build, no one released such a built, not even for beta testing yet so...
