### ISSUE TITLE
Nether portal link problem 1.18

### ISSUE THREAD

**Issue by GroGaloraGran** [Multiverse/Multiverse-NetherPortals#240]
### Information

* **Server version: This server is running Paper version git-Paper-19 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 892c292)** 

* **Full output of `/mv version -p`:** *https://paste.gg/p/anonymous/d8942cb352ef4621abd4d05fc3bd38ba* 

* **Server log:** *https://gist.github.com/GroGaloraGran/5fe9d7665c76d61c180d038776f6b543* 

### Details
I can reproduce this issue when all plugins are enabled. The problem does not appear when the Multiverse-NetherPortals v4.2.1 plugin is disabled, but then another problem appears - in the second world the portal to the Nether of the second world does not work and leads to the nether of the first world.

**description**
*In our upper world, a gold farm was created on Nether portals, for which a "service" portal was left in Nether, which was Linked with the farm portals. Below in Nether and a little to the side there is a metro line with a portal through which you can get to the farm.
If we return from the upper world to Nether through the correct portal, we find ourselves in the service portal in Nether (this is dangerous due to the aggressive zombie pig)
here is no problem with the disabled plugin Multiverse-NetherPortals v4.2.1, but we have an additional world with our own Nether world, and if we try to get from the additional world (let it be World2) and its world2_Nether with the plugin disabled, then for some reason we find ourselves in world_nether ((*  

**Steps to reproduce**  
farm created in 1.16.5 portals are connected
1. Exit from Nether to the upper world - to approach the farm, aside.
2. Portals of the farm with a separate Portal in Nether (by coordinates)
after the "transition" to 1.18 with the plugin enabled:
When leaving Nether to the upper world, we will find ourselves several levels below the previously created portal.
If you go to Nether from the previously created portal, we get to the "service" portal tied to the farm

**Expected behavior**  
It is expected that the snapping of portals by coordinates will be preserved, That is, the output of a particular portal will lead to where it was snapped earlier.

**Screenshots**  
do not take a screenshot for this (

**Comment by GroGaloraGran** [comment]
Hey
to confirm the anomaly, I made an additional video
Logs and videos using the Multiverse-NetherPortals plugin
https://youtu.be/OzTZgKUTZc4
https://gist.github.com/GroGaloraGran/75e7c5648cc5d3f7ef4bef29240b484c
Logs and videos with disabled plugin
https://youtu.be/DQRweOETx5s
https://gist.github.com/GroGaloraGran/78330ebcbe7425fe40277e0d9663551e
this is what is on our assembly at the moment, with the latest test core Paper 1.18.1 # 71

**Comment by GroGaloraGran** [comment]
Hello. Happy Holidays. Can I get feedback from you? This is an important plugin for us and without it we cannot properly update our server to 1.18.1 thanks

**Comment by nicegamer7** [comment]
I've watched the videos you uploaded and it helps explain the issue, thanks for that.

What's the value of `level-name` in `server.properties`?

**Comment by GroGaloraGran** [comment]
Hello
level-name = world

**Comment by nicegamer7** [comment]
I'm closing this in favour of #244.
