### ISSUE TITLE
Portals created in the nether and are far away from any active portals in the overworld do not work at all (even when linked using the command)

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Multiverse/Multiverse-NetherPortals#241]
### Information

* **Server version:** 3352-Spigot-dbf4938-f49e9d1 (MC: 1.18)

* **Full output of `/mv version -p`:** Not possible, prints "Error posting to service" error in the console.

* **Server log:** [latest.log](https://github.com/Multiverse/Multiverse-NetherPortals/files/7677025/latest.log)

### Details
I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Nether Portals made in the nether far away from any linked overworld portal will not work at all.

**Steps to reproduce**  
Make a nether portal in the nether, far away from any active nether portal in the overworld. It won't be able to teleport you.

**Expected behavior**  
For the portals to work like normal nether portals do using the plugin.

**Screenshots**  
![2021-12-08_16 25 08](https://user-images.githubusercontent.com/11783274/145234976-d66a70cd-ee2a-4002-964a-5df2930d3045.png)

**Comment by nicegamer7** [comment]
I couldn't reproduce the behaviour you mentioned. Try running `/mvv -p` again, and if it gives you an error send your `latest.log` file.
