### ISSUE TITLE
[Bug]: Multiverse-NetherPortals linking Nether Portals incorrectly in 1.18.1

### ISSUE THREAD

**Issue by DJSorad** [Multiverse/Multiverse-NetherPortals#244]
### `/mv version -p` output

https://pastebin.com/7pShjDD1

### Server logs

https://pastebin.com/7x6yE50Z

### Server Version

```shell
This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)
You are 31 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-132 (MC: 1.17.1)
```

### Nether portal data

    Nether portal A in the overworld
        X: -750
        Y: 64
        Z: -518
    Nether portal B in the Nether
        X: -114
        Y: 90
        Z: -3
    Nether portal B converted to coords in the overworld (multiplied by 8)
        X: -912
        Y: 90
        Z: -24
    Distances in each coords of Nether portal A and B in the overworld
        X: 912 - 750 = 162
        Y: 90 - 64 = 16
        Z: 518 - 24 = 494
    Max cubic distance between portal A and B overworld locations
        sqrt(162^2 + 16^2 + 494^2) = 520.13
    Teleports to Nether portal C in the overworld after stepping into Nether portal B
        X: -933
        Y: 74
        Z: -134

### Behavior after MV on the same server

When stepping into portal A, it sends you to portal B (a portal generated in the nether from portal C). When stepping into portal B, it teleports to portal C. This issue is preventing multiple nether portals to be linked correctly.

### Steps to reproduce

1. Create a portal in the Overworld (Portal C)
2. Step into Portal C to generate Portal B in the Nether.
3. Step back into Portal B to return to Overworld.
4. Create a new portal roughly 425.5 cubic distance apart (Portal A)
5. Step into Portal A, this should generate a new portal in the Nether but instead teleports to Portal B in the Nether.
6. Step into Portal B which takes you back to Portal C.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by JamesRagnarok** [comment]
> Didn't have time to test 😔.
> 
> From a quick glance though, I was slightly suspicious of the location scaling code. Here's a test build of MV-NP with that code changed. I don't expect it fix this issue, but if it does... nice lol.
> 
> [Multiverse-NetherPortals-4.2.2-SNAPSHOT.zip](https://github.com/Multiverse/Multiverse-Core/files/8037148/Multiverse-NetherPortals-4.2.2-SNAPSHOT.zip)

A quick test with this snapshot fixed the issue on my server with Paper build 187. I'm going to create more worlds for further tests.

**Comment by nicegamer7** [comment]
![](https://c.tenor.com/HSRFAMWw5RkAAAAC/shocked-face-shock.gif)

**Comment by JamesRagnarok** [comment]
This reminds me that one of my portal links was disrupted way back in 1.16 with MV. I moved that portal vertically for a few blocks and fixed that issue.

**Comment by nicegamer7** [comment]
I suppose that makes sense now 😅.

**Comment by berlincount** [comment]
It also seems to have addressed the problems on our server.
