### ISSUE TITLE
How to automatically generate portals and link portals to them?

### ISSUE THREAD

**Issue by Anglophobia** [Multiverse/Multiverse-NetherPortals#248]
Hello, when players in my server use the nether portal to the nether, they will teleport to a set spawn location. The portals are linked both ways and I have no clue on how to make them automattically generate. The players needs to be able to teleport to the other portal like in vanilla minecraft. I dont remember changing anything about these settings

**Comment by TharkNethIta** [comment]
i'm searching for same thing

**Comment by zax71** [comment]
Please send your `/mvv -p` link

**Comment by zax71** [comment]
Closing as stale
