### ISSUE TITLE
INFO java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by tskopen** [Multiverse/Multiverse-NetherPortals#249]
### Information

* **Server version:** v4.2.2-b807

* **Full output of [`/mv version -p`:** [](https://mcpaste.io/8b1e34c901f7a5c6)](https://paste.gg/p/anonymous/25662d07a4494279a535465de1c3c6b8)

* **Server log:** https://gist.github.com/tskopen/4f0ac31fb5a7edd0b5e0af64964ae7e5

### Details
I was unable to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
  Plugin doesn't work and give internal errors https://mcpaste.io/10a3ba5051926e5f

**Steps to reproduce**  
updated to 1.18.2 paper

**Expected behavior**  
sorta excepted some plugins to die

**Screenshots**  
not needed

**Comment by benwoo1110** [comment]
Likely not an mv issue. You can read this article on some suggested solutions https://madelinemiller.dev/blog/minecraft-zip-file-closed/

**Comment by tskopen** [comment]
ok thanks
