### ISSUE TITLE
unloading/deleing default nether breaks all nether portals no matter where they are linked.

### ISSUE THREAD

**Issue by TomLewis** [Multiverse/Multiverse-NetherPortals#253]
### Information

* **Server version:** Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Purpur-1628 (MC: 1.18.2)
* You are running the latest version

* **Full output of `/mv version -p`:**  Why are you publishing seeds public? Why is this not removed when you run this command? Why cant I delete the paste once its been pasted? I wasn't sent a key. 

* **Server log:** n/a

### Details
I was **able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
I have 4 worlds.
Worldname_1
Worldname_1_nether
Worldname_1_nether2
Worldname_1_the_end

Im using this plugin to redirect nether portals from Worldname_1 to Worldname_1_nether2, I no longer need Worldname_1_nether.

When I unload Worldname_1_nether it breaks ALL nether portals across the world.

**Steps to reproduce**  
Unload your vanilla nether world from multiverse, which breaks all portals working even tho they are linked.

**Expected behavior**  
To not break portals and let us use whatever nether world name we want

**Comment by nicegamer7** [comment]
This was a change that Spigot made in 1.16. The default nether and end worlds are required for portals to work.

**Comment by TomLewis** [comment]
Well that sucks.
