### ISSUE TITLE
Multiverse-NetherPortals won't work when allow-nether and allow-end is set to false.

### ISSUE THREAD

**Issue by matipoirierg** [Multiverse/Multiverse-NetherPortals#254]
Hi I wanted to not use the default world_nether and world_the_end worlds, instead I wanted to use another nether and end worlds called EndWorld and NetherWorld, so I set  allow-nether and allow-end to false to avoid the generation of the defaults nether and end worlds, and then I linked my overworld to EndWorld and NetherWorld, but portals just don't work.

**Comment by ToxykAuBleu** [comment]
Hi 👋 Same problem for me, I was thinking it was related to my server's version (even when the plugin is loaded and both specific worlds are linked correctly in the config), I think it's not 🤷‍♂️

**Comment by nicegamer7** [comment]
This was a change that Spigot made in 1.16. `allow-nether` and `allow-end` are required for portals to work.
