### ISSUE TITLE
Unescapable end! End portal and mvtp not working, just teleports me on top of the dragon egg!

### ISSUE THREAD

**Issue by GergosGames** [Multiverse/Multiverse-NetherPortals#255]
### Information

* **Server version:** git-Paper-141 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 51183af)

* **Full output of `/mv version -p`:** (https://paste.gg/p/anonymous/5cfd2fd9ec6e4fda9def9233922604ae)

* **Server log:** (https://paste.gg/p/anonymous/5cfd2fd9ec6e4fda9def9233922604ae)

### Help request

**Problem**
I have 3 worlds in my server (that the problem is related to, there are other worlds):
SMP_1_OVERWORLD
SMP_1_NETHER
SMP_1_END

I have linked them properly using /mvnp link and when I go through a nether portal in the overworld, it takes me to the nether, and vice versa. But when I go to the end(which also works perfectly) I cannot get out.

**What I have tried**
I have tried to jump through the middle portal, and use /mvtp SMP_1_OVERWORLD and /mvtp SMP_1_NETHER but they all just teleport me on top of the egg.

**Comment by benwoo1110** [comment]
Seem like an issue with mv-inv config, you need to add SMP_1_END to your smp_1 world group

```
  smp_1:
    worlds:
    - smp_1_nether
    - hub_nether
    - smp_1_overworld
    shares:
    - all
```
