### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alexchandel** [Multiverse/Multiverse-NetherPortals#257]
Could you publish a new release, either on GitHub (which has none) or dev.bukkit.org?

dev.bukkit.org was last updated 2022-03-12 to 4.2.2, and even the dev builds only go up to 4.2.3-SNAPSHOT.  Multiverse-Core is on 4.3.1, and interplugin compatibility is unclear.

This project's readme, for example, has no information at all.

**Comment by zax71** [comment]
All the latest versions can always work together. No need to publish a new release when there are no changes
