### ISSUE TITLE
Need help to setup the plugin

### ISSUE THREAD

**Issue by NoltoxGit** [Multiverse/Multiverse-NetherPortals#264]
### Information

* **Server version:**
version
[23:05:44 INFO]: Checking version, please wait...
[23:05:44 INFO]: Current: git-Purpur-2143 (MC: 1.20.4)*
Previous: git-Purpur-2142 (MC: 1.20.4)
You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/af622a3e59404c8fbfa1ab1c226a88a4

* **Server log:** https://mclo.gs/0DvkX2l

### Help request

**Problem**
I need help with my Nether world,

I have 2 normal worlds on my server called `Survival` & `Harvest` and 1 nether world called `Nether`.

But I don't understand how to configure `Multiverse-NetherPortals` to make it work :/

**What I have tried**
I've tried to link but i don't understand.

**Screenshots**

**Comment by NeverGrowUp** [comment]
`/mvnplink nether survie nether` then `/mvnplink nether nether survie`

All info is on the wiki. https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(NetherPortals)#customizing-linking
