### ISSUE TITLE
Lone nether portal blocks can send creative mode players into the end

### ISSUE THREAD

**Issue by Saposhiente** [Multiverse/Multiverse-NetherPortals#62]
If you are in creative and enter a portal from above (like an end portal) in some funkily specific manner, you will be sent to the end. Not a vanilla bug nor a bukkit bug.
Two methods:
Method 1: Flymod + Gamemode change
Step 1: Build a standard nether portal structure, but instead of lighting it, place a single portal block (block 90) in a bottom corner.
Step 2: Stand in the other half of the portal.
Step 3: While in survival mode, use flymod to levitate until you hit the roof of the portal. (You can float for limited amounts of time even on allow-flight:false servers)
Step 4: Move to over the portal block.
Step 5: Change gamemode to creative.
This will either put you in the end, or attempt to put you in the end, throw an exception, and disconnect you. Which one seems to be dependent on portal location, but unsure.
Method 2: Trapdoor lag
Step 1: Build a 1-tick-clock
Step 2: Power a trapdoor with the clock
Step 3: Place a portal block (block 90) next to and below the trapdoor
Step 4: Jump on the trapdoor repeatedly until you experience lag, teleporting up and down (plugins will see PlayerTeleportEvents from the trapdoor pushing you around). You may need to move back and forth or jump off then jump back on again. If you stop experiencing lag that's great, you just need to have experienced lag and not touched the ground before going to the portal.
Step 5: Jump on the portal. When you don't miss, this method will always send you to the end.
![2012-12-21_19 27 16](https://f.cloud.github.com/assets/1591208/28279/95a06caa-4be7-11e2-929f-ba5171ac6800.png)

**Comment by zax71** [comment]
I could not reproduce this in 1.21
