### ISSUE TITLE
Nether Portals Launch people

### ISSUE THREAD

**Issue by FlawlessSin** [Multiverse/Multiverse-NetherPortals#64]
Whenever Non-OP people come into close proximity with a netherportal, they are hurt and are launch some 5-20 blocks away.

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
