### ISSUE TITLE
Nether portals are broken no portal is created

### ISSUE THREAD

**Issue by ezebtron** [Multiverse/Multiverse-NetherPortals#68]
whenever i make a nether portal on my second world and go through it no portal is created on the other side in my second world's nether. I just spawn in mid air and fall to my death or spawn in the terrain no portal is made. Because of this i entered in creative mode to make one to see if they would link and they did not even though i made it right next to where i was spawning in the nether it just sent me to a random far off place in the overworld

**Comment by clabe45** [comment]
> @HammyHavoc are you referring to the beta build on dev.bukkit.org or a dev build on ci.onarandombox.com?

I just confirmed that version 2.5-b675 (beta) on dev.bukkit.org works.

**Comment by HammyHavoc** [comment]
@clabe45 Whatever was current on Feb 14 2014.
