### ISSUE TITLE
Two End Worlds, One End World Not Linking

### ISSUE THREAD

**Issue by Coldcarp1** [Multiverse/Multiverse-NetherPortals#81]
Here is an issue that we are having on my server.  

We have two seperate worlds that each have their own individual nether and end.  The two nethers work correctly with no issues.  However, we have two end worlds as well.  One end world works fine, but the other end world does not.  It won't let anyone teleport to the world with an end portal.  The configs look like we linked them properly. 

Thanks!  Let me know if you need further explanation.

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
