### ISSUE TITLE
Could not load config.yml

### ISSUE THREAD

**Issue by hiimtoby** [Multiverse/Multiverse-NetherPortals#83]
I installed MVNP and it just hasn't worked, I have linked worlds and built the portal but you cant go through them, the screen just keeps swirling.  I have tried the DEV builds and it doesn't make a difference. And no one else on the forum seems to have this problem...  I'm not sure if it's conflicting with another plugin, but if it is can you please try and tell me which one! 
:)
Thanks in advance

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
