### ISSUE TITLE
#80 continued

### ISSUE THREAD

**Issue by lipe123** [Multiverse/Multiverse-NetherPortals#85]
Just installed the latest dev's
Multiverse-Core Version: 2.5-b687
Multiverse-NetherPortals Version: 2.5-b680

Went into the portal in my home(536, 187) -> goes to nether
Go back into portal, in the nether -> goes to a field (587, 262)
Go in field portal, goes to the same nether gate as my house, and returns to it no problem. 

So is there a config setting that needs working on or whats going on here?
like these(from my config):
  defaultportalsearch: 'false'
  portalsearchradius: '16'

**Comment by gabessdsp** [comment]
What was the fix for this? The twitch link is dead now

**Comment by lipe123** [comment]
I don't host a server anymore. my "fix" was to use a different multi world handler in the end, I cant even remember what the name of it was though.

**Comment by gabessdsp** [comment]
Darn :/ I'm hating these nether portal issues

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
