### ISSUE TITLE
End portals leads to the void

### ISSUE THREAD

**Issue by furest** [Multiverse/Multiverse-NetherPortals#91]
When I go into the portal (linked to the same world + "_the_end" it leads me to the void. At the same coordinates as on the dungeon.
What's the way to do as if It was directly created and so it leads me on the true ground near the dragon.
I'm really getting stucked with it in my server...
Version of MV plugins: http://pastie.org/private/xw42bnzmwkiyqxrgmd3tag
Logs: / => that's not an error in the console, it just leads me to the exact coordinates and I can't go to where the "default" portal would. (that's not a portal I created.)
Config file is blank because I use the way of [worldname]_the_end linking.
Furest

**Comment by roopekoo** [comment]
Latest dev build https://ci.onarandombox.com/job/Multiverse-NetherPortals/ makes obsidian floor when teleporting to the end. If you even have this problem after 4 years...

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
