### ISSUE TITLE
End portals will not link to The End

### ISSUE THREAD

**Issue by davkas2005** [Multiverse/Multiverse-NetherPortals#95]
Mutilverse-Core version:  2.5-b678 (beta)
Multiverse-Portals version: 2.5-b699 (beta)
Multiverse-NetherPortals version: 2.5-b675 (beta)
CraftBukkit version: Beta 1.7.2-R0.3

My original world, called bukkittest, will not link to the end world I created for it, called bukkittest_the_end. When I try to link the end portals in bukkittest to bukkittest_the_end using the following command:

/mvnp link end bukkittest bukkittest_the_end

nothing happens. If I list the links, the above link does not show in the list even though it shows up in the Multiverse-NetherPortals config.yml file. I drop right through the vanilla-generated end portal without getting teleported anywhere. I'm opped on this server and am not using any custom permissions.

**Comment by sargunster** [comment]
I'm having a similar issue. End link just don't work.
The command `/mvnp show` only shows nether links, not end links. 
The command `/mvnp show end` will show the end links, but they still don't actually work.

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
