### ISSUE TITLE
not making portal

### ISSUE THREAD

**Issue by ghost** [Multiverse/Multiverse-NetherPortals#96]
how do I make it so the plugin can make portals, I own a skyblock server and it keeps spawning me really high in the nether, always in the same spot and it doesn't make a new portal

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
