### ISSUE TITLE
Items won't go thru Nether Portals.

### ISSUE THREAD

**Issue by smartn1nja** [Multiverse/Multiverse-NetherPortals#97]
Items won't go thru Nether Portals. This only happens to worlds that are not "world" and "world_nether". Obviously Multiverse-NetherPortals bug please fix ASAP :)

**Comment by gabessdsp** [comment]
Or obviously it's your problem for not using a world-inventories plugin. Use Multiverse-Inventories or Multiinv

**Comment by dali99** [comment]
I think this is probably a duplicate of #72

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
