### ISSUE TITLE
I spawn in the air when using end portal

### ISSUE THREAD

**Issue by galqawala** [Multiverse/Multiverse-NetherPortals#98]
I used MV on a fresh server to create 3 worlds in addition to the 3 original ones. I built an end portal in "worldGravity". When I use it, it takes me to "worldGravity_the_end" but I spawn in mid air and take damage when falling down. I tried using command "/mv setspawn" in a safe place in "worldGravity_the_end", but it only affects "/mv tp worldGravity_the_end" command, not the portal. I'm out of clues, what else could I try?

Startup log: http://pastebin.com/YjKW0Lqd .

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
