### ISSUE TITLE
org.bukkit.event.world.PortalCreateEvent doesn't get called when portal gets generated.

### ISSUE THREAD

**Issue by Tibowl** [Multiverse/Multiverse-NetherPortals#99]
PortalCreateEvent doesn't get fired when a portal gets generated from teleporting from (custom) world worldTest -> worldTest_nether.

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
